<?php
    use App\Category;
    use App\Booking;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\DB;

    // get sevice fee percentage
    if(!function_exists('serviceFee')){
        function serviceFee(){
            $deductionPercentage;
            DB::table('tb_fee')->first()!=null ? $deductionPercentage = DB::table('tb_fee')->first()->fee : $deductionPercentage = 20; 
            return $deductionPercentage; 
        }
    }

    // check image exist or not
    if(function_exists('imageExists')){
        function imageExists($filePath)
        {
            $header_response = get_headers($filePath, 1);
            return strpos($header_response[0], "404") !== false ? false:true;
        }
    }

    if(!function_exists('getTimeZoneTime'))
    {
        function getTimeZoneTime($ftz,$ttz,$time)
        {
            date_default_timezone_set($ftz);
            $datetime = new DateTime($time);
            $la_time = new DateTimeZone($ttz);
            $datetime->setTimezone($la_time);
            return date("g:i A", strtotime($datetime->format('H:i')));
        }
    }

    if(!function_exists('getTimeZoneDate'))
    {
        function getTimeZoneDate($ftz,$ttz,$date)
        {
            date_default_timezone_set($ftz);
            $datetime = new DateTime($date);
            $la_time = new DateTimeZone($ttz);
            $datetime->setTimezone($la_time);
            return date("d M Y", strtotime($date));
        }
    }

    if(!function_exists('getCurrentUserTimeZone'))
    {
        function getCurrentUserTimeZone(){
            if(config('app.live_ip_check')=='local')
            {
                $ip = file_get_contents("http://ipecho.net/plain");
                $url = 'http://ip-api.com/json/'.$ip;
                $tz = file_get_contents($url);
                $tz = json_decode($tz,true)['timezone'];
                return $tz;
            }
            else if(config('app.live_ip_check')=='live')
            {
                $ip = \Request::getClientIp(true);
                $url = 'http://ip-api.com/json/'.$ip;
                $curl = curl_init();
                curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                curl_setopt($curl, CURLOPT_URL, $url);
                curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
                curl_setopt($curl, CURLOPT_HTTPHEADER, array("content-type: application/json"));
                $response = curl_exec($curl);
                curl_close($curl);
                $tz = json_decode($response,true)['timezone'];
                return $tz;
            }
            
        }
    }

    if(!function_exists('categories'))
    {
        function categories()
        {
            return Category::whereNotIn('title',['all','All'])->inRandomOrder()->get();
        }
    }

    if(!function_exists('subCategories'))
    {
        function subCategories()
        {
            return Category::where('is_subcategory','!=','0')->whereNotIn('title',['all','All'])->inRandomOrder()->get();
        }
    }

    if(!function_exists('parentCategories'))
    {
        function parentCategories()
        {
            return Category::where('is_subcategory','0')->whereNotIn('title',['all','All'])->inRandomOrder()->get();
        }
    }

    if(!function_exists('countries'))
    {
        function countries()
        {
            // return  array("Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao, People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");
            return array(
                array("country_code" => "AF", "name" => "Afghanistan", "code" => "93"),
                array("country_code" => "AL", "name" => "Albania", "code" => "355"),
                array("country_code" => "DZ", "name" => "Algeria", "code" => "213"),
                array("country_code" => "AS", "name" => "American Samoa", "code" => "1"),
                array("country_code" => "AD", "name" => "Andorra", "code" => "376"),
                array("country_code" => "AO", "name" => "Angola", "code" => "244"),
                array("country_code" => "AI", "name" => "Anguilla", "code" => "1"),
                array("country_code" => "AG", "name" => "Antigua", "code" => "1"),
                array("country_code" => "AR", "name" => "Argentina", "code" => "54"),
                array("country_code" => "AM", "name" => "Armenia", "code" => "374"),
                array("country_code" => "AW", "name" => "Aruba", "code" => "297"),
                array("country_code" => "AU", "name" => "Australia", "code" => "61"),
                array("country_code" => "AT", "name" => "Austria", "code" => "43"),
                array("country_code" => "AZ", "name" => "Azerbaijan", "code" => "994"),
                array("country_code" => "BH", "name" => "Bahrain", "code" => "973"),
                array("country_code" => "BD", "name" => "Bangladesh", "code" => "880"),
                array("country_code" => "BB", "name" => "Barbados", "code" => "1"),
                array("country_code" => "BY", "name" => "Belarus", "code" => "375"),
                array("country_code" => "BE", "name" => "Belgium", "code" => "32"),
                array("country_code" => "BZ", "name" => "Belize", "code" => "501"),
                array("country_code" => "BJ", "name" => "Benin", "code" => "229"),
                array("country_code" => "BM", "name" => "Bermuda", "code" => "1"),
                array("country_code" => "BT", "name" => "Bhutan", "code" => "975"),
                array("country_code" => "BO", "name" => "Bolivia", "code" => "591"),
                array("country_code" => "BA", "name" => "Bosnia and Herzegovina", "code" => "387"),
                array("country_code" => "BW", "name" => "Botswana", "code" => "267"),
                array("country_code" => "BR", "name" => "Brazil", "code" => "55"),
                array("country_code" => "IO", "name" => "British Indian Ocean Territory", "code" => "246"),
                array("country_code" => "VG", "name" => "British Virgin Islands", "code" => "1"),
                array("country_code" => "BN", "name" => "Brunei", "code" => "673"),
                array("country_code" => "BG", "name" => "Bulgaria", "code" => "359"),
                array("country_code" => "BF", "name" => "Burkina Faso", "code" => "226"),
                array("country_code" => "MM", "name" => "Burma Myanmar", "code" => "95"),
                array("country_code" => "BI", "name" => "Burundi", "code" => "257"),
                array("country_code" => "KH", "name" => "Cambodia", "code" => "855"),
                array("country_code" => "CM", "name" => "Cameroon", "code" => "237"),
                array("country_code" => "CA", "name" => "Canada", "code" => "1"),
                array("country_code" => "CV", "name" => "Cape Verde", "code" => "238"),
                array("country_code" => "KY", "name" => "Cayman Islands", "code" => "1"),
                array("country_code" => "CF", "name" => "Central African Republic", "code" => "236"),
                array("country_code" => "TD", "name" => "Chad", "code" => "235"),
                array("country_code" => "CL", "name" => "Chile", "code" => "56"),
                array("country_code" => "CN", "name" => "China", "code" => "86"),
                array("country_code" => "CO", "name" => "Colombia", "code" => "57"),
                array("country_code" => "KM", "name" => "Comoros", "code" => "269"),
                array("country_code" => "CK", "name" => "Cook Islands", "code" => "682"),
                array("country_code" => "CR", "name" => "Costa Rica", "code" => "506"),
                array("country_code" => "CI", "name" => "Côte d'Ivoire", "code" => "225"),
                array("country_code" => "HR", "name" => "Croatia", "code" => "385"),
                array("country_code" => "CU", "name" => "Cuba", "code" => "53"),
                array("country_code" => "CY", "name" => "Cyprus", "code" => "357"),
                array("country_code" => "CZ", "name" => "Czech Republic", "code" => "420"),
                array("country_code" => "CD", "name" => "Democratic Republic of Congo", "code" => "243"),
                array("country_code" => "DK", "name" => "Denmark", "code" => "45"),
                array("country_code" => "DJ", "name" => "Djibouti", "code" => "253"),
                array("country_code" => "DM", "name" => "Dominica", "code" => "1"),
                array("country_code" => "DO", "name" => "Dominican Republic", "code" => "1"),
                array("country_code" => "EC", "name" => "Ecuador", "code" => "593"),
                array("country_code" => "EG", "name" => "Egypt", "code" => "20"),
                array("country_code" => "SV", "name" => "El Salvador", "code" => "503"),
                array("country_code" => "GQ", "name" => "Equatorial Guinea", "code" => "240"),
                array("country_code" => "ER", "name" => "Eritrea", "code" => "291"),
                array("country_code" => "EE", "name" => "Estonia", "code" => "372"),
                array("country_code" => "ET", "name" => "Ethiopia", "code" => "251"),
                array("country_code" => "FK", "name" => "Falkland Islands", "code" => "500"),
                array("country_code" => "FO", "name" => "Faroe Islands", "code" => "298"),
                array("country_code" => "FM", "name" => "Federated States of Micronesia", "code" => "691"),
                array("country_code" => "FJ", "name" => "Fiji", "code" => "679"),
                array("country_code" => "FI", "name" => "Finland", "code" => "358"),
                array("country_code" => "FR", "name" => "France", "code" => "33"),
                array("country_code" => "GF", "name" => "French Guiana", "code" => "594"),
                array("country_code" => "PF", "name" => "French Polynesia", "code" => "689"),
                array("country_code" => "GA", "name" => "Gabon", "code" => "241"),
                array("country_code" => "GE", "name" => "Georgia", "code" => "995"),
                array("country_code" => "DE", "name" => "Germany", "code" => "49"),
                array("country_code" => "GH", "name" => "Ghana", "code" => "233"),
                array("country_code" => "GI", "name" => "Gibraltar", "code" => "350"),
                array("country_code" => "GR", "name" => "Greece", "code" => "30"),
                array("country_code" => "GL", "name" => "Greenland", "code" => "299"),
                array("country_code" => "GD", "name" => "Grenada", "code" => "1"),
                array("country_code" => "GP", "name" => "Guadeloupe", "code" => "590"),
                array("country_code" => "GU", "name" => "Guam", "code" => "1"),
                array("country_code" => "GT", "name" => "Guatemala", "code" => "502"),
                array("country_code" => "GN", "name" => "Guinea", "code" => "224"),
                array("country_code" => "GW", "name" => "Guinea-Bissau", "code" => "245"),
                array("country_code" => "GY", "name" => "Guyana", "code" => "592"),
                array("country_code" => "HT", "name" => "Haiti", "code" => "509"),
                array("country_code" => "HN", "name" => "Honduras", "code" => "504"),
                array("country_code" => "HK", "name" => "Hong Kong", "code" => "852"),
                array("country_code" => "HU", "name" => "Hungary", "code" => "36"),
                array("country_code" => "IS", "name" => "Iceland", "code" => "354"),
                array("country_code" => "IN", "name" => "India", "code" => "91"),
                array("country_code" => "ID", "name" => "Indonesia", "code" => "62"),
                array("country_code" => "IR", "name" => "Iran", "code" => "98"),
                array("country_code" => "IQ", "name" => "Iraq", "code" => "964"),
                array("country_code" => "IE", "name" => "Ireland", "code" => "353"),
                array("country_code" => "IL", "name" => "Israel", "code" => "972"),
                array("country_code" => "IT", "name" => "Italy", "code" => "39"),
                array("country_code" => "JM", "name" => "Jamaica", "code" => "1"),
                array("country_code" => "JP", "name" => "Japan", "code" => "81"),
                array("country_code" => "JO", "name" => "Jordan", "code" => "962"),
                array("country_code" => "KZ", "name" => "Kazakhstan", "code" => "7"),
                array("country_code" => "KE", "name" => "Kenya", "code" => "254"),
                array("country_code" => "KI", "name" => "Kiribati", "code" => "686"),
                array("country_code" => "XK", "name" => "Kosovo", "code" => "381"),
                array("country_code" => "KW", "name" => "Kuwait", "code" => "965"),
                array("country_code" => "KG", "name" => "Kyrgyzstan", "code" => "996"),
                array("country_code" => "LA", "name" => "Laos", "code" => "856"),
                array("country_code" => "LV", "name" => "Latvia", "code" => "371"),
                array("country_code" => "LB", "name" => "Lebanon", "code" => "961"),
                array("country_code" => "LS", "name" => "Lesotho", "code" => "266"),
                array("country_code" => "LR", "name" => "Liberia", "code" => "231"),
                array("country_code" => "LY", "name" => "Libya", "code" => "218"),
                array("country_code" => "LI", "name" => "Liechtenstein", "code" => "423"),
                array("country_code" => "LT", "name" => "Lithuania", "code" => "370"),
                array("country_code" => "LU", "name" => "Luxembourg", "code" => "352"),
                array("country_code" => "MO", "name" => "Macau", "code" => "853"),
                array("country_code" => "MK", "name" => "Macedonia", "code" => "389"),
                array("country_code" => "MG", "name" => "Madagascar", "code" => "261"),
                array("country_code" => "MW", "name" => "Malawi", "code" => "265"),
                array("country_code" => "MY", "name" => "Malaysia", "code" => "60"),
                array("country_code" => "MV", "name" => "Maldives", "code" => "960"),
                array("country_code" => "ML", "name" => "Mali", "code" => "223"),
                array("country_code" => "MT", "name" => "Malta", "code" => "356"),
                array("country_code" => "MH", "name" => "Marshall Islands", "code" => "692"),
                array("country_code" => "MQ", "name" => "Martinique", "code" => "596"),
                array("country_code" => "MR", "name" => "Mauritania", "code" => "222"),
                array("country_code" => "MU", "name" => "Mauritius", "code" => "230"),
                array("country_code" => "YT", "name" => "Mayotte", "code" => "262"),
                array("country_code" => "MX", "name" => "Mexico", "code" => "52"),
                array("country_code" => "MD", "name" => "Moldova", "code" => "373"),
                array("country_code" => "MC", "name" => "Monaco", "code" => "377"),
                array("country_code" => "MN", "name" => "Mongolia", "code" => "976"),
                array("country_code" => "ME", "name" => "Montenegro", "code" => "382"),
                array("country_code" => "MS", "name" => "Montserrat", "code" => "1"),
                array("country_code" => "MA", "name" => "Morocco", "code" => "212"),
                array("country_code" => "MZ", "name" => "Mozambique", "code" => "258"),
                array("country_code" => "NA", "name" => "Namibia", "code" => "264"),
                array("country_code" => "NR", "name" => "Nauru", "code" => "674"),
                array("country_code" => "NP", "name" => "Nepal", "code" => "977"),
                array("country_code" => "NL", "name" => "Netherlands", "code" => "31"),
                array("country_code" => "AN", "name" => "Netherlands Antilles", "code" => "599"),
                array("country_code" => "NC", "name" => "New Caledonia", "code" => "687"),
                array("country_code" => "NZ", "name" => "New Zealand", "code" => "64"),
                array("country_code" => "NI", "name" => "Nicaragua", "code" => "505"),
                array("country_code" => "NE", "name" => "Niger", "code" => "227"),
                array("country_code" => "NG", "name" => "Nigeria", "code" => "234"),
                array("country_code" => "NU", "name" => "Niue", "code" => "683"),
                array("country_code" => "NF", "name" => "Norfolk Island", "code" => "672"),
                array("country_code" => "KP", "name" => "North Korea", "code" => "850"),
                array("country_code" => "MP", "name" => "Northern Mariana Islands", "code" => "1"),
                array("country_code" => "NO", "name" => "Norway", "code" => "47"),
                array("country_code" => "OM", "name" => "Oman", "code" => "968"),
                array("country_code" => "PK", "name" => "Pakistan", "code" => "92"),
                array("country_code" => "PW", "name" => "Palau", "code" => "680"),
                array("country_code" => "PS", "name" => "Palestine", "code" => "970"),
                array("country_code" => "PA", "name" => "Panama", "code" => "507"),
                array("country_code" => "PG", "name" => "Papua New Guinea", "code" => "675"),
                array("country_code" => "PY", "name" => "Paraguay", "code" => "595"),
                array("country_code" => "PE", "name" => "Peru", "code" => "51"),
                array("country_code" => "PH", "name" => "Philippines", "code" => "63"),
                array("country_code" => "PL", "name" => "Poland", "code" => "48"),
                array("country_code" => "PT", "name" => "Portugal", "code" => "351"),
                array("country_code" => "PR", "name" => "Puerto Rico", "code" => "1"),
                array("country_code" => "QA", "name" => "Qatar", "code" => "974"),
                array("country_code" => "CG", "name" => "Republic of the Congo", "code" => "242"),
                array("country_code" => "RE", "name" => "Réunion", "code" => "262"),
                array("country_code" => "RO", "name" => "Romania", "code" => "40"),
                array("country_code" => "RU", "name" => "Russia", "code" => "7"),
                array("country_code" => "RW", "name" => "Rwanda", "code" => "250"),
                array("country_code" => "BL", "name" => "Saint Barthélemy", "code" => "590"),
                array("country_code" => "SH", "name" => "Saint Helena", "code" => "290"),
                array("country_code" => "KN", "name" => "Saint Kitts and Nevis", "code" => "1"),
                array("country_code" => "MF", "name" => "Saint Martin", "code" => "590"),
                array("country_code" => "PM", "name" => "Saint Pierre and Miquelon", "code" => "508"),
                array("country_code" => "VC", "name" => "Saint Vincent and the Grenadines", "code" => "1"),
                array("country_code" => "WS", "name" => "Samoa", "code" => "685"),
                array("country_code" => "SM", "name" => "San Marino", "code" => "378"),
                array("country_code" => "ST", "name" => "São Tomé and Príncipe", "code" => "239"),
                array("country_code" => "SA", "name" => "Saudi Arabia", "code" => "966"),
                array("country_code" => "SN", "name" => "Senegal", "code" => "221"),
                array("country_code" => "RS", "name" => "Serbia", "code" => "381"),
                array("country_code" => "SC", "name" => "Seychelles", "code" => "248"),
                array("country_code" => "SL", "name" => "Sierra Leone", "code" => "232"),
                array("country_code" => "SG", "name" => "Singapore", "code" => "65"),
                array("country_code" => "SK", "name" => "Slovakia", "code" => "421"),
                array("country_code" => "SI", "name" => "Slovenia", "code" => "386"),
                array("country_code" => "SB", "name" => "Solomon Islands", "code" => "677"),
                array("country_code" => "SO", "name" => "Somalia", "code" => "252"),
                array("country_code" => "ZA", "name" => "South Africa", "code" => "27"),
                array("country_code" => "KR", "name" => "South Korea", "code" => "82"),
                array("country_code" => "ES", "name" => "Spain", "code" => "34"),
                array("country_code" => "LK", "name" => "Sri Lanka", "code" => "94"),
                array("country_code" => "LC", "name" => "St. Lucia", "code" => "1"),
                array("country_code" => "SD", "name" => "Sudan", "code" => "249"),
                array("country_code" => "SR", "name" => "Suriname", "code" => "597"),
                array("country_code" => "SZ", "name" => "Swaziland", "code" => "268"),
                array("country_code" => "SE", "name" => "Sweden", "code" => "46"),
                array("country_code" => "CH", "name" => "Switzerland", "code" => "41"),
                array("country_code" => "SY", "name" => "Syria", "code" => "963"),
                array("country_code" => "TW", "name" => "Taiwan", "code" => "886"),
                array("country_code" => "TJ", "name" => "Tajikistan", "code" => "992"),
                array("country_code" => "TZ", "name" => "Tanzania", "code" => "255"),
                array("country_code" => "TH", "name" => "Thailand", "code" => "66"),
                array("country_code" => "BS", "name" => "The Bahamas", "code" => "1"),
                array("country_code" => "GM", "name" => "The Gambia", "code" => "220"),
                array("country_code" => "TL", "name" => "Timor-Leste", "code" => "670"),
                array("country_code" => "TG", "name" => "Togo", "code" => "228"),
                array("country_code" => "TK", "name" => "Tokelau", "code" => "690"),
                array("country_code" => "TO", "name" => "Tonga", "code" => "676"),
                array("country_code" => "TT", "name" => "Trinidad and Tobago", "code" => "1"),
                array("country_code" => "TN", "name" => "Tunisia", "code" => "216"),
                array("country_code" => "TR", "name" => "Turkey", "code" => "90"),
                array("country_code" => "TM", "name" => "Turkmenistan", "code" => "993"),
                array("country_code" => "TC", "name" => "Turks and Caicos Islands", "code" => "1"),
                array("country_code" => "TV", "name" => "Tuvalu", "code" => "688"),
                array("country_code" => "UG", "name" => "Uganda", "code" => "256"),
                array("country_code" => "UA", "name" => "Ukraine", "code" => "380"),
                array("country_code" => "AE", "name" => "United Arab Emirates", "code" => "971"),
                array("country_code" => "GB", "name" => "United Kingdom", "code" => "44"),
                array("country_code" => "US", "name" => "United States", "code" => "1"),
                array("country_code" => "UY", "name" => "Uruguay", "code" => "598"),
                array("country_code" => "VI", "name" => "US Virgin Islands", "code" => "1"),
                array("country_code" => "UZ", "name" => "Uzbekistan", "code" => "998"),
                array("country_code" => "VU", "name" => "Vanuatu", "code" => "678"),
                array("country_code" => "VA", "name" => "Vatican City", "code" => "39"),
                array("country_code" => "VE", "name" => "Venezuela", "code" => "58"),
                array("country_code" => "VN", "name" => "Vietnam", "code" => "84"),
                array("country_code" => "WF", "name" => "Wallis and Futuna", "code" => "681"),
                array("country_code" => "YE", "name" => "Yemen", "code" => "967"),
                array("country_code" => "ZM", "name" => "Zambia", "code" => "260"),
                array("country_code" => "ZW", "name" => "Zimbabwe", "code" => "263"),
            );
            
            return array(
                'AD'=>array('name'=>'ANDORRA','code'=>'376'),
                'AF'=>array('name'=>'AFGHANISTAN','code'=>'93'),
                'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
                'AI'=>array('name'=>'ANGUILLA','code'=>'1264'),
                'AL'=>array('name'=>'ALBANIA','code'=>'355'),
                'AM'=>array('name'=>'ARMENIA','code'=>'374'),
                'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'599'),
                'AO'=>array('name'=>'ANGOLA','code'=>'244'),
                'AQ'=>array('name'=>'ANTARCTICA','code'=>'672'),
                'AR'=>array('name'=>'ARGENTINA','code'=>'54'),
                'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'1684'),
                'AT'=>array('name'=>'AUSTRIA','code'=>'43'),
                'AU'=>array('name'=>'AUSTRALIA','code'=>'61'),
                'AW'=>array('name'=>'ARUBA','code'=>'297'),
                'AZ'=>array('name'=>'AZERBAIJAN','code'=>'994'),
                'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
                'BB'=>array('name'=>'BARBADOS','code'=>'1246'),
                'BD'=>array('name'=>'BANGLADESH','code'=>'880'),
                'BE'=>array('name'=>'BELGIUM','code'=>'32'),
                'BF'=>array('name'=>'BURKINA FASO','code'=>'226'),
                'BG'=>array('name'=>'BULGARIA','code'=>'359'),
                'BH'=>array('name'=>'BAHRAIN','code'=>'973'),
                'BI'=>array('name'=>'BURUNDI','code'=>'257'),
                'BJ'=>array('name'=>'BENIN','code'=>'229'),
                'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'590'),
                'BM'=>array('name'=>'BERMUDA','code'=>'1441'),
                'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'673'),
                'BO'=>array('name'=>'BOLIVIA','code'=>'591'),
                'BR'=>array('name'=>'BRAZIL','code'=>'55'),
                'BS'=>array('name'=>'BAHAMAS','code'=>'1242'),
                'BT'=>array('name'=>'BHUTAN','code'=>'975'),
                'BW'=>array('name'=>'BOTSWANA','code'=>'267'),
                'BY'=>array('name'=>'BELARUS','code'=>'375'),
                'BZ'=>array('name'=>'BELIZE','code'=>'501'),
                'CA'=>array('name'=>'CANADA','code'=>'1'),
                'CC'=>array('name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
                'CD'=>array('name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
                'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
                'CG'=>array('name'=>'CONGO','code'=>'242'),
                'CH'=>array('name'=>'SWITZERLAND','code'=>'41'),
                'CI'=>array('name'=>'COTE D IVOIRE','code'=>'225'),
                'CK'=>array('name'=>'COOK ISLANDS','code'=>'682'),
                'CL'=>array('name'=>'CHILE','code'=>'56'),
                'CM'=>array('name'=>'CAMEROON','code'=>'237'),
                'CN'=>array('name'=>'CHINA','code'=>'86'),
                'CO'=>array('name'=>'COLOMBIA','code'=>'57'),
                'CR'=>array('name'=>'COSTA RICA','code'=>'506'),
                'CU'=>array('name'=>'CUBA','code'=>'53'),
                'CV'=>array('name'=>'CAPE VERDE','code'=>'238'),
                'CX'=>array('name'=>'CHRISTMAS ISLAND','code'=>'61'),
                'CY'=>array('name'=>'CYPRUS','code'=>'357'),
                'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'420'),
                'DE'=>array('name'=>'GERMANY','code'=>'49'),
                'DJ'=>array('name'=>'DJIBOUTI','code'=>'253'),
                'DK'=>array('name'=>'DENMARK','code'=>'45'),
                'DM'=>array('name'=>'DOMINICA','code'=>'1767'),
                'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
                'DZ'=>array('name'=>'ALGERIA','code'=>'213'),
                'EC'=>array('name'=>'ECUADOR','code'=>'593'),
                'EE'=>array('name'=>'ESTONIA','code'=>'372'),
                'EG'=>array('name'=>'EGYPT','code'=>'20'),
                'ER'=>array('name'=>'ERITREA','code'=>'291'),
                'ES'=>array('name'=>'SPAIN','code'=>'34'),
                'ET'=>array('name'=>'ETHIOPIA','code'=>'251'),
                'FI'=>array('name'=>'FINLAND','code'=>'358'),
                'FJ'=>array('name'=>'FIJI','code'=>'679'),
                'FK'=>array('name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
                'FM'=>array('name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
                'FO'=>array('name'=>'FAROE ISLANDS','code'=>'298'),
                'FR'=>array('name'=>'FRANCE','code'=>'33'),
                'GA'=>array('name'=>'GABON','code'=>'241'),
                'GB'=>array('name'=>'UNITED KINGDOM','code'=>'44'),
                'GD'=>array('name'=>'GRENADA','code'=>'1473'),
                'GE'=>array('name'=>'GEORGIA','code'=>'995'),
                'GH'=>array('name'=>'GHANA','code'=>'233'),
                'GI'=>array('name'=>'GIBRALTAR','code'=>'350'),
                'GL'=>array('name'=>'GREENLAND','code'=>'299'),
                'GM'=>array('name'=>'GAMBIA','code'=>'220'),
                'GN'=>array('name'=>'GUINEA','code'=>'224'),
                'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'240'),
                'GR'=>array('name'=>'GREECE','code'=>'30'),
                'GT'=>array('name'=>'GUATEMALA','code'=>'502'),
                'GU'=>array('name'=>'GUAM','code'=>'1671'),
                'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'245'),
                'GY'=>array('name'=>'GUYANA','code'=>'592'),
                'HK'=>array('name'=>'HONG KONG','code'=>'852'),
                'HN'=>array('name'=>'HONDURAS','code'=>'504'),
                'HR'=>array('name'=>'CROATIA','code'=>'385'),
                'HT'=>array('name'=>'HAITI','code'=>'509'),
                'HU'=>array('name'=>'HUNGARY','code'=>'36'),
                'ID'=>array('name'=>'INDONESIA','code'=>'62'),
                'IE'=>array('name'=>'IRELAND','code'=>'353'),
                'IL'=>array('name'=>'ISRAEL','code'=>'972'),
                'IM'=>array('name'=>'ISLE OF MAN','code'=>'44'),
                'IN'=>array('name'=>'INDIA','code'=>'91'),
                'IQ'=>array('name'=>'IRAQ','code'=>'964'),
                'IR'=>array('name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
                'IS'=>array('name'=>'ICELAND','code'=>'354'),
                'IT'=>array('name'=>'ITALY','code'=>'39'),
                'JM'=>array('name'=>'JAMAICA','code'=>'1876'),
                'JO'=>array('name'=>'JORDAN','code'=>'962'),
                'JP'=>array('name'=>'JAPAN','code'=>'81'),
                'KE'=>array('name'=>'KENYA','code'=>'254'),
                'KG'=>array('name'=>'KYRGYZSTAN','code'=>'996'),
                'KH'=>array('name'=>'CAMBODIA','code'=>'855'),
                'KI'=>array('name'=>'KIRIBATI','code'=>'686'),
                'KM'=>array('name'=>'COMOROS','code'=>'269'),
                'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
                'KP'=>array('name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
                'KR'=>array('name'=>'KOREA REPUBLIC OF','code'=>'82'),
                'KW'=>array('name'=>'KUWAIT','code'=>'965'),
                'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'1345'),
                'KZ'=>array('name'=>'KAZAKSTAN','code'=>'7'),
                'LA'=>array('name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
                'LB'=>array('name'=>'LEBANON','code'=>'961'),
                'LC'=>array('name'=>'SAINT LUCIA','code'=>'1758'),
                'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'423'),
                'LK'=>array('name'=>'SRI LANKA','code'=>'94'),
                'LR'=>array('name'=>'LIBERIA','code'=>'231'),
                'LS'=>array('name'=>'LESOTHO','code'=>'266'),
                'LT'=>array('name'=>'LITHUANIA','code'=>'370'),
                'LU'=>array('name'=>'LUXEMBOURG','code'=>'352'),
                'LV'=>array('name'=>'LATVIA','code'=>'371'),
                'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
                'MA'=>array('name'=>'MOROCCO','code'=>'212'),
                'MC'=>array('name'=>'MONACO','code'=>'377'),
                'MD'=>array('name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
                'ME'=>array('name'=>'MONTENEGRO','code'=>'382'),
                'MF'=>array('name'=>'SAINT MARTIN','code'=>'1599'),
                'MG'=>array('name'=>'MADAGASCAR','code'=>'261'),
                'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'692'),
                'MK'=>array('name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
                'ML'=>array('name'=>'MALI','code'=>'223'),
                'MM'=>array('name'=>'MYANMAR','code'=>'95'),
                'MN'=>array('name'=>'MONGOLIA','code'=>'976'),
                'MO'=>array('name'=>'MACAU','code'=>'853'),
                'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
                'MR'=>array('name'=>'MAURITANIA','code'=>'222'),
                'MS'=>array('name'=>'MONTSERRAT','code'=>'1664'),
                'MT'=>array('name'=>'MALTA','code'=>'356'),
                'MU'=>array('name'=>'MAURITIUS','code'=>'230'),
                'MV'=>array('name'=>'MALDIVES','code'=>'960'),
                'MW'=>array('name'=>'MALAWI','code'=>'265'),
                'MX'=>array('name'=>'MEXICO','code'=>'52'),
                'MY'=>array('name'=>'MALAYSIA','code'=>'60'),
                'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'258'),
                'NA'=>array('name'=>'NAMIBIA','code'=>'264'),
                'NC'=>array('name'=>'NEW CALEDONIA','code'=>'687'),
                'NE'=>array('name'=>'NIGER','code'=>'227'),
                'NG'=>array('name'=>'NIGERIA','code'=>'234'),
                'NI'=>array('name'=>'NICARAGUA','code'=>'505'),
                'NL'=>array('name'=>'NETHERLANDS','code'=>'31'),
                'NO'=>array('name'=>'NORWAY','code'=>'47'),
                'NP'=>array('name'=>'NEPAL','code'=>'977'),
                'NR'=>array('name'=>'NAURU','code'=>'674'),
                'NU'=>array('name'=>'NIUE','code'=>'683'),
                'NZ'=>array('name'=>'NEW ZEALAND','code'=>'64'),
                'OM'=>array('name'=>'OMAN','code'=>'968'),
                'PA'=>array('name'=>'PANAMA','code'=>'507'),
                'PE'=>array('name'=>'PERU','code'=>'51'),
                'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'689'),
                'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'675'),
                'PH'=>array('name'=>'PHILIPPINES','code'=>'63'),
                'PK'=>array('name'=>'PAKISTAN','code'=>'92'),
                'PL'=>array('name'=>'POLAND','code'=>'48'),
                'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
                'PN'=>array('name'=>'PITCAIRN','code'=>'870'),
                'PR'=>array('name'=>'PUERTO RICO','code'=>'1'),
                'PT'=>array('name'=>'PORTUGAL','code'=>'351'),
                'PW'=>array('name'=>'PALAU','code'=>'680'),
                'PY'=>array('name'=>'PARAGUAY','code'=>'595'),
                'QA'=>array('name'=>'QATAR','code'=>'974'),
                'RO'=>array('name'=>'ROMANIA','code'=>'40'),
                'RS'=>array('name'=>'SERBIA','code'=>'381'),
                'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'7'),
                'RW'=>array('name'=>'RWANDA','code'=>'250'),
                'SA'=>array('name'=>'SAUDI ARABIA','code'=>'966'),
                'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'677'),
                'SC'=>array('name'=>'SEYCHELLES','code'=>'248'),
                'SD'=>array('name'=>'SUDAN','code'=>'249'),
                'SE'=>array('name'=>'SWEDEN','code'=>'46'),
                'SG'=>array('name'=>'SINGAPORE','code'=>'65'),
                'SH'=>array('name'=>'SAINT HELENA','code'=>'290'),
                'SI'=>array('name'=>'SLOVENIA','code'=>'386'),
                'SK'=>array('name'=>'SLOVAKIA','code'=>'421'),
                'SL'=>array('name'=>'SIERRA LEONE','code'=>'232'),
                'SM'=>array('name'=>'SAN MARINO','code'=>'378'),
                'SN'=>array('name'=>'SENEGAL','code'=>'221'),
                'SO'=>array('name'=>'SOMALIA','code'=>'252'),
                'SR'=>array('name'=>'SURINAME','code'=>'597'),
                'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
                'SV'=>array('name'=>'EL SALVADOR','code'=>'503'),
                'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
                'SZ'=>array('name'=>'SWAZILAND','code'=>'268'),
                'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
                'TD'=>array('name'=>'CHAD','code'=>'235'),
                'TG'=>array('name'=>'TOGO','code'=>'228'),
                'TH'=>array('name'=>'THAILAND','code'=>'66'),
                'TJ'=>array('name'=>'TAJIKISTAN','code'=>'992'),
                'TK'=>array('name'=>'TOKELAU','code'=>'690'),
                'TL'=>array('name'=>'TIMOR-LESTE','code'=>'670'),
                'TM'=>array('name'=>'TURKMENISTAN','code'=>'993'),
                'TN'=>array('name'=>'TUNISIA','code'=>'216'),
                'TO'=>array('name'=>'TONGA','code'=>'676'),
                'TR'=>array('name'=>'TURKEY','code'=>'90'),
                'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
                'TV'=>array('name'=>'TUVALU','code'=>'688'),
                'TW'=>array('name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
                'TZ'=>array('name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
                'UA'=>array('name'=>'UKRAINE','code'=>'380'),
                'UG'=>array('name'=>'UGANDA','code'=>'256'),
                'US'=>array('name'=>'UNITED STATES','code'=>'1'),
                'UY'=>array('name'=>'URUGUAY','code'=>'598'),
                'UZ'=>array('name'=>'UZBEKISTAN','code'=>'998'),
                'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
                'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
                'VE'=>array('name'=>'VENEZUELA','code'=>'58'),
                'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
                'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
                'VN'=>array('name'=>'VIET NAM','code'=>'84'),
                'VU'=>array('name'=>'VANUATU','code'=>'678'),
                'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'681'),
                'WS'=>array('name'=>'SAMOA','code'=>'685'),
                'XK'=>array('name'=>'KOSOVO','code'=>'383'),
                'YE'=>array('name'=>'YEMEN','code'=>'967'),
                'YT'=>array('name'=>'MAYOTTE','code'=>'262'),
                'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'27'),
                'ZM'=>array('name'=>'ZAMBIA','code'=>'260'),
                'ZW'=>array('name'=>'ZIMBABWE','code'=>'263')
            );
        }
    }

    if(!function_exists('getTimeZoneList'))
    {
        function getTimeZoneList()
        {
             return  array(
                'America/Adak' => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)',
                'America/Atka' => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)',
                'America/Anchorage' => '(GMT-9:00) America/Anchorage (Alaska Standard Time)',
                'America/Juneau' => '(GMT-9:00) America/Juneau (Alaska Standard Time)',
                'America/Nome' => '(GMT-9:00) America/Nome (Alaska Standard Time)',
                'America/Yakutat' => '(GMT-9:00) America/Yakutat (Alaska Standard Time)',
                'America/Dawson' => '(GMT-8:00) America/Dawson (Pacific Standard Time)',
                'America/Ensenada' => '(GMT-8:00) America/Ensenada (Pacific Standard Time)',
                'America/Los_Angeles' => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)',
                'America/Tijuana' => '(GMT-8:00) America/Tijuana (Pacific Standard Time)',
                'America/Vancouver' => '(GMT-8:00) America/Vancouver (Pacific Standard Time)',
                'America/Whitehorse' => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)',
                'Canada/Pacific' => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)',
                'Canada/Yukon' => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)',
                'Mexico/BajaNorte' => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)',
                'America/Boise' => '(GMT-7:00) America/Boise (Mountain Standard Time)',
                'America/Cambridge_Bay' => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)',
                'America/Chihuahua' => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)',
                'America/Dawson_Creek' => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)',
                'America/Denver' => '(GMT-7:00) America/Denver (Mountain Standard Time)',
                'America/Edmonton' => '(GMT-7:00) America/Edmonton (Mountain Standard Time)',
                'America/Hermosillo' => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)',
                'America/Inuvik' => '(GMT-7:00) America/Inuvik (Mountain Standard Time)',
                'America/Mazatlan' => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)',
                'America/Phoenix' => '(GMT-7:00) America/Phoenix (Mountain Standard Time)',
                'America/Shiprock' => '(GMT-7:00) America/Shiprock (Mountain Standard Time)',
                'America/Yellowknife' => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)',
                'Canada/Mountain' => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)',
                'Mexico/BajaSur' => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)',
                'America/Belize' => '(GMT-6:00) America/Belize (Central Standard Time)',
                'America/Cancun' => '(GMT-6:00) America/Cancun (Central Standard Time)',
                'America/Chicago' => '(GMT-6:00) America/Chicago (Central Standard Time)',
                'America/Costa_Rica' => '(GMT-6:00) America/Costa_Rica (Central Standard Time)',
                'America/El_Salvador' => '(GMT-6:00) America/El_Salvador (Central Standard Time)',
                'America/Guatemala' => '(GMT-6:00) America/Guatemala (Central Standard Time)',
                'America/Knox_IN' => '(GMT-6:00) America/Knox_IN (Central Standard Time)',
                'America/Managua' => '(GMT-6:00) America/Managua (Central Standard Time)',
                'America/Menominee' => '(GMT-6:00) America/Menominee (Central Standard Time)',
                'America/Merida' => '(GMT-6:00) America/Merida (Central Standard Time)',
                'America/Mexico_City' => '(GMT-6:00) America/Mexico_City (Central Standard Time)',
                'America/Monterrey' => '(GMT-6:00) America/Monterrey (Central Standard Time)',
                'America/Rainy_River' => '(GMT-6:00) America/Rainy_River (Central Standard Time)',
                'America/Rankin_Inlet' => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)',
                'America/Regina' => '(GMT-6:00) America/Regina (Central Standard Time)',
                'America/Swift_Current' => '(GMT-6:00) America/Swift_Current (Central Standard Time)',
                'America/Tegucigalpa' => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)',
                'America/Winnipeg' => '(GMT-6:00) America/Winnipeg (Central Standard Time)',
                'Canada/Central' => '(GMT-6:00) Canada/Central (Central Standard Time)',
                'Canada/East-Saskatchewan' => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)',
                'Canada/Saskatchewan' => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)',
                'Chile/EasterIsland' => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)',
                'Mexico/General' => '(GMT-6:00) Mexico/General (Central Standard Time)',
                'America/Atikokan' => '(GMT-5:00) America/Atikokan (Eastern Standard Time)',
                'America/Bogota' => '(GMT-5:00) America/Bogota (Colombia Time)',
                'America/Cayman' => '(GMT-5:00) America/Cayman (Eastern Standard Time)',
                'America/Coral_Harbour' => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)',
                'America/Detroit' => '(GMT-5:00) America/Detroit (Eastern Standard Time)',
                'America/Fort_Wayne' => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)',
                'America/Grand_Turk' => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)',
                'America/Guayaquil' => '(GMT-5:00) America/Guayaquil (Ecuador Time)',
                'America/Havana' => '(GMT-5:00) America/Havana (Cuba Standard Time)',
                'America/Indianapolis' => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)',
                'America/Iqaluit' => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)',
                'America/Jamaica' => '(GMT-5:00) America/Jamaica (Eastern Standard Time)',
                'America/Lima' => '(GMT-5:00) America/Lima (Peru Time)',
                'America/Louisville' => '(GMT-5:00) America/Louisville (Eastern Standard Time)',
                'America/Montreal' => '(GMT-5:00) America/Montreal (Eastern Standard Time)',
                'America/Nassau' => '(GMT-5:00) America/Nassau (Eastern Standard Time)',
                'America/New_York' => '(GMT-5:00) America/New_York (Eastern Standard Time)',
                'America/Nipigon' => '(GMT-5:00) America/Nipigon (Eastern Standard Time)',
                'America/Panama' => '(GMT-5:00) America/Panama (Eastern Standard Time)',
                'America/Pangnirtung' => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)',
                'America/Port-au-Prince' => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)',
                'America/Resolute' => '(GMT-5:00) America/Resolute (Eastern Standard Time)',
                'America/Thunder_Bay' => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)',
                'America/Toronto' => '(GMT-5:00) America/Toronto (Eastern Standard Time)',
                'Canada/Eastern' => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)',
                'America/Caracas' => '(GMT-4:-30) America/Caracas (Venezuela Time)',
                'America/Anguilla' => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)',
                'America/Antigua' => '(GMT-4:00) America/Antigua (Atlantic Standard Time)',
                'America/Aruba' => '(GMT-4:00) America/Aruba (Atlantic Standard Time)',
                'America/Asuncion' => '(GMT-4:00) America/Asuncion (Paraguay Time)',
                'America/Barbados' => '(GMT-4:00) America/Barbados (Atlantic Standard Time)',
                'America/Blanc-Sablon' => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)',
                'America/Boa_Vista' => '(GMT-4:00) America/Boa_Vista (Amazon Time)',
                'America/Campo_Grande' => '(GMT-4:00) America/Campo_Grande (Amazon Time)',
                'America/Cuiaba' => '(GMT-4:00) America/Cuiaba (Amazon Time)',
                'America/Curacao' => '(GMT-4:00) America/Curacao (Atlantic Standard Time)',
                'America/Dominica' => '(GMT-4:00) America/Dominica (Atlantic Standard Time)',
                'America/Eirunepe' => '(GMT-4:00) America/Eirunepe (Amazon Time)',
                'America/Glace_Bay' => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)',
                'America/Goose_Bay' => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)',
                'America/Grenada' => '(GMT-4:00) America/Grenada (Atlantic Standard Time)',
                'America/Guadeloupe' => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)',
                'America/Guyana' => '(GMT-4:00) America/Guyana (Guyana Time)',
                'America/Halifax' => '(GMT-4:00) America/Halifax (Atlantic Standard Time)',
                'America/La_Paz' => '(GMT-4:00) America/La_Paz (Bolivia Time)',
                'America/Manaus' => '(GMT-4:00) America/Manaus (Amazon Time)',
                'America/Marigot' => '(GMT-4:00) America/Marigot (Atlantic Standard Time)',
                'America/Martinique' => '(GMT-4:00) America/Martinique (Atlantic Standard Time)',
                'America/Moncton' => '(GMT-4:00) America/Moncton (Atlantic Standard Time)',
                'America/Montserrat' => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)',
                'America/Port_of_Spain' => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)',
                'America/Porto_Acre' => '(GMT-4:00) America/Porto_Acre (Amazon Time)',
                'America/Porto_Velho' => '(GMT-4:00) America/Porto_Velho (Amazon Time)',
                'America/Puerto_Rico' => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)',
                'America/Rio_Branco' => '(GMT-4:00) America/Rio_Branco (Amazon Time)',
                'America/Santiago' => '(GMT-4:00) America/Santiago (Chile Time)',
                'America/Santo_Domingo' => '(GMT-4:00) America/Santo_Domingo (Atlantic Standard Time)',
                'America/St_Barthelemy' => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)',
                'America/St_Kitts' => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)',
                'America/St_Lucia' => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)',
                'America/St_Thomas' => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)',
                'America/St_Vincent' => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)',
                'America/Thule' => '(GMT-4:00) America/Thule (Atlantic Standard Time)',
                'America/Tortola' => '(GMT-4:00) America/Tortola (Atlantic Standard Time)',
                'America/Virgin' => '(GMT-4:00) America/Virgin (Atlantic Standard Time)',
                'Antarctica/Palmer' => '(GMT-4:00) Antarctica/Palmer (Chile Time)',
                'Atlantic/Bermuda' => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)',
                'Atlantic/Stanley' => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)',
                'Brazil/Acre' => '(GMT-4:00) Brazil/Acre (Amazon Time)',
                'Brazil/West' => '(GMT-4:00) Brazil/West (Amazon Time)',
                'Canada/Atlantic' => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)',
                'Chile/Continental' => '(GMT-4:00) Chile/Continental (Chile Time)',
                'America/St_Johns' => '(GMT-3:-30) America/St_Johns (Newfoundland Standard Time)',
                'Canada/Newfoundland' => '(GMT-3:-30) Canada/Newfoundland (Newfoundland Standard Time)',
                'America/Araguaina' => '(GMT-3:00) America/Araguaina (Brasilia Time)',
                'America/Bahia' => '(GMT-3:00) America/Bahia (Brasilia Time)',
                'America/Belem' => '(GMT-3:00) America/Belem (Brasilia Time)',
                'America/Buenos_Aires' => '(GMT-3:00) America/Buenos_Aires (Argentine Time)',
                'America/Catamarca' => '(GMT-3:00) America/Catamarca (Argentine Time)',
                'America/Cayenne' => '(GMT-3:00) America/Cayenne (French Guiana Time)',
                'America/Cordoba' => '(GMT-3:00) America/Cordoba (Argentine Time)',
                'America/Fortaleza' => '(GMT-3:00) America/Fortaleza (Brasilia Time)',
                'America/Godthab' => '(GMT-3:00) America/Godthab (Western Greenland Time)',
                'America/Jujuy' => '(GMT-3:00) America/Jujuy (Argentine Time)',
                'America/Maceio' => '(GMT-3:00) America/Maceio (Brasilia Time)',
                'America/Mendoza' => '(GMT-3:00) America/Mendoza (Argentine Time)',
                'America/Miquelon' => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)',
                'America/Montevideo' => '(GMT-3:00) America/Montevideo (Uruguay Time)',
                'America/Paramaribo' => '(GMT-3:00) America/Paramaribo (Suriname Time)',
                'America/Recife' => '(GMT-3:00) America/Recife (Brasilia Time)',
                'America/Rosario' => '(GMT-3:00) America/Rosario (Argentine Time)',
                'America/Santarem' => '(GMT-3:00) America/Santarem (Brasilia Time)',
                'America/Sao_Paulo' => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)',
                'Antarctica/Rothera' => '(GMT-3:00) Antarctica/Rothera (Rothera Time)',
                'Brazil/East' => '(GMT-3:00) Brazil/East (Brasilia Time)',
                'America/Noronha' => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)',
                'Atlantic/South_Georgia' => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)',
                'Brazil/DeNoronha' => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)',
                'America/Scoresbysund' => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)',
                'Atlantic/Azores' => '(GMT-1:00) Atlantic/Azores (Azores Time)',
                'Atlantic/Cape_Verde' => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)',
                'Africa/Abidjan' => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)',
                'Africa/Accra' => '(GMT+0:00) Africa/Accra (Ghana Mean Time)',
                'Africa/Bamako' => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)',
                'Africa/Banjul' => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)',
                'Africa/Bissau' => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)',
                'Africa/Casablanca' => '(GMT+0:00) Africa/Casablanca (Western European Time)',
                'Africa/Conakry' => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)',
                'Africa/Dakar' => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)',
                'Africa/El_Aaiun' => '(GMT+0:00) Africa/El_Aaiun (Western European Time)',
                'Africa/Freetown' => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)',
                'Africa/Lome' => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)',
                'Africa/Monrovia' => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)',
                'Africa/Nouakchott' => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)',
                'Africa/Ouagadougou' => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)',
                'Africa/Sao_Tome' => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)',
                'Africa/Timbuktu' => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)',
                'America/Danmarkshavn' => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)',
                'Atlantic/Canary' => '(GMT+0:00) Atlantic/Canary (Western European Time)',
                'Atlantic/Faeroe' => '(GMT+0:00) Atlantic/Faeroe (Western European Time)',
                'Atlantic/Faroe' => '(GMT+0:00) Atlantic/Faroe (Western European Time)',
                'Atlantic/Madeira' => '(GMT+0:00) Atlantic/Madeira (Western European Time)',
                'Atlantic/Reykjavik' => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)',
                'Atlantic/St_Helena' => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)',
                'Europe/Belfast' => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)',
                'Europe/Dublin' => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)',
                'Europe/Guernsey' => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)',
                'Europe/Isle_of_Man' => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)',
                'Europe/Jersey' => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)',
                'Europe/Lisbon' => '(GMT+0:00) Europe/Lisbon (Western European Time)',
                'Europe/London' => '(GMT+0:00) Europe/London (Greenwich Mean Time)',
                'Africa/Algiers' => '(GMT+1:00) Africa/Algiers (Central European Time)',
                'Africa/Bangui' => '(GMT+1:00) Africa/Bangui (Western African Time)',
                'Africa/Brazzaville' => '(GMT+1:00) Africa/Brazzaville (Western African Time)',
                'Africa/Ceuta' => '(GMT+1:00) Africa/Ceuta (Central European Time)',
                'Africa/Douala' => '(GMT+1:00) Africa/Douala (Western African Time)',
                'Africa/Kinshasa' => '(GMT+1:00) Africa/Kinshasa (Western African Time)',
                'Africa/Lagos' => '(GMT+1:00) Africa/Lagos (Western African Time)',
                'Africa/Libreville' => '(GMT+1:00) Africa/Libreville (Western African Time)',
                'Africa/Luanda' => '(GMT+1:00) Africa/Luanda (Western African Time)',
                'Africa/Malabo' => '(GMT+1:00) Africa/Malabo (Western African Time)',
                'Africa/Ndjamena' => '(GMT+1:00) Africa/Ndjamena (Western African Time)',
                'Africa/Niamey' => '(GMT+1:00) Africa/Niamey (Western African Time)',
                'Africa/Porto-Novo' => '(GMT+1:00) Africa/Porto-Novo (Western African Time)',
                'Africa/Tunis' => '(GMT+1:00) Africa/Tunis (Central European Time)',
                'Africa/Windhoek' => '(GMT+1:00) Africa/Windhoek (Western African Time)',
                'Arctic/Longyearbyen' => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)',
                'Atlantic/Jan_Mayen' => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)',
                'Europe/Amsterdam' => '(GMT+1:00) Europe/Amsterdam (Central European Time)',
                'Europe/Andorra' => '(GMT+1:00) Europe/Andorra (Central European Time)',
                'Europe/Belgrade' => '(GMT+1:00) Europe/Belgrade (Central European Time)',
                'Europe/Berlin' => '(GMT+1:00) Europe/Berlin (Central European Time)',
                'Europe/Bratislava' => '(GMT+1:00) Europe/Bratislava (Central European Time)',
                'Europe/Brussels' => '(GMT+1:00) Europe/Brussels (Central European Time)',
                'Europe/Budapest' => '(GMT+1:00) Europe/Budapest (Central European Time)',
                'Europe/Copenhagen' => '(GMT+1:00) Europe/Copenhagen (Central European Time)',
                'Europe/Gibraltar' => '(GMT+1:00) Europe/Gibraltar (Central European Time)',
                'Europe/Ljubljana' => '(GMT+1:00) Europe/Ljubljana (Central European Time)',
                'Europe/Luxembourg' => '(GMT+1:00) Europe/Luxembourg (Central European Time)',
                'Europe/Madrid' => '(GMT+1:00) Europe/Madrid (Central European Time)',
                'Europe/Malta' => '(GMT+1:00) Europe/Malta (Central European Time)',
                'Europe/Monaco' => '(GMT+1:00) Europe/Monaco (Central European Time)',
                'Europe/Oslo' => '(GMT+1:00) Europe/Oslo (Central European Time)',
                'Europe/Paris' => '(GMT+1:00) Europe/Paris (Central European Time)',
                'Europe/Podgorica' => '(GMT+1:00) Europe/Podgorica (Central European Time)',
                'Europe/Prague' => '(GMT+1:00) Europe/Prague (Central European Time)',
                'Europe/Rome' => '(GMT+1:00) Europe/Rome (Central European Time)',
                'Europe/San_Marino' => '(GMT+1:00) Europe/San_Marino (Central European Time)',
                'Europe/Sarajevo' => '(GMT+1:00) Europe/Sarajevo (Central European Time)',
                'Europe/Skopje' => '(GMT+1:00) Europe/Skopje (Central European Time)',
                'Europe/Stockholm' => '(GMT+1:00) Europe/Stockholm (Central European Time)',
                'Europe/Tirane' => '(GMT+1:00) Europe/Tirane (Central European Time)',
                'Europe/Vaduz' => '(GMT+1:00) Europe/Vaduz (Central European Time)',
                'Europe/Vatican' => '(GMT+1:00) Europe/Vatican (Central European Time)',
                'Europe/Vienna' => '(GMT+1:00) Europe/Vienna (Central European Time)',
                'Europe/Warsaw' => '(GMT+1:00) Europe/Warsaw (Central European Time)',
                'Europe/Zagreb' => '(GMT+1:00) Europe/Zagreb (Central European Time)',
                'Europe/Zurich' => '(GMT+1:00) Europe/Zurich (Central European Time)',
                'Africa/Blantyre' => '(GMT+2:00) Africa/Blantyre (Central African Time)',
                'Africa/Bujumbura' => '(GMT+2:00) Africa/Bujumbura (Central African Time)',
                'Africa/Cairo' => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
                'Africa/Gaborone' => '(GMT+2:00) Africa/Gaborone (Central African Time)',
                'Africa/Harare' => '(GMT+2:00) Africa/Harare (Central African Time)',
                'Africa/Johannesburg' => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)',
                'Africa/Kigali' => '(GMT+2:00) Africa/Kigali (Central African Time)',
                'Africa/Lubumbashi' => '(GMT+2:00) Africa/Lubumbashi (Central African Time)',
                'Africa/Lusaka' => '(GMT+2:00) Africa/Lusaka (Central African Time)',
                'Africa/Maputo' => '(GMT+2:00) Africa/Maputo (Central African Time)',
                'Africa/Maseru' => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)',
                'Africa/Mbabane' => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)',
                'Africa/Tripoli' => '(GMT+2:00) Africa/Tripoli (Eastern European Time)',
                'Asia/Amman' => '(GMT+2:00) Asia/Amman (Eastern European Time)',
                'Asia/Beirut' => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
                'Asia/Damascus' => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
                'Asia/Gaza' => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
                'Asia/Istanbul' => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
                'Asia/Jerusalem' => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
                'Asia/Nicosia' => '(GMT+2:00) Asia/Nicosia (Eastern European Time)',
                'Asia/Tel_Aviv' => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)',
                'Europe/Athens' => '(GMT+2:00) Europe/Athens (Eastern European Time)',
                'Europe/Bucharest' => '(GMT+2:00) Europe/Bucharest (Eastern European Time)',
                'Europe/Chisinau' => '(GMT+2:00) Europe/Chisinau (Eastern European Time)',
                'Europe/Helsinki' => '(GMT+2:00) Europe/Helsinki (Eastern European Time)',
                'Europe/Istanbul' => '(GMT+2:00) Europe/Istanbul (Eastern European Time)',
                'Europe/Kaliningrad' => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)',
                'Europe/Kiev' => '(GMT+2:00) Europe/Kiev (Eastern European Time)',
                'Europe/Mariehamn' => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)',
                'Europe/Minsk' => '(GMT+2:00) Europe/Minsk (Eastern European Time)',
                'Europe/Nicosia' => '(GMT+2:00) Europe/Nicosia (Eastern European Time)',
                'Europe/Riga' => '(GMT+2:00) Europe/Riga (Eastern European Time)',
                'Europe/Simferopol' => '(GMT+2:00) Europe/Simferopol (Eastern European Time)',
                'Europe/Sofia' => '(GMT+2:00) Europe/Sofia (Eastern European Time)',
                'Europe/Tallinn' => '(GMT+2:00) Europe/Tallinn (Eastern European Time)',
                'Europe/Tiraspol' => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)',
                'Europe/Uzhgorod' => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)',
                'Europe/Vilnius' => '(GMT+2:00) Europe/Vilnius (Eastern European Time)',
                'Europe/Zaporozhye' => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)',
                'Africa/Addis_Ababa' => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)',
                'Africa/Asmara' => '(GMT+3:00) Africa/Asmara (Eastern African Time)',
                'Africa/Asmera' => '(GMT+3:00) Africa/Asmera (Eastern African Time)',
                'Africa/Dar_es_Salaam' => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
                'Africa/Djibouti' => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
                'Africa/Kampala' => '(GMT+3:00) Africa/Kampala (Eastern African Time)',
                'Africa/Khartoum' => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
                'Africa/Mogadishu' => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
                'Africa/Nairobi' => '(GMT+3:00) Africa/Nairobi (Eastern African Time)',
                'Antarctica/Syowa' => '(GMT+3:00) Antarctica/Syowa (Syowa Time)',
                'Asia/Aden' => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
                'Asia/Baghdad' => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
                'Asia/Bahrain' => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
                'Asia/Kuwait' => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
                'Asia/Qatar' => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
                'Europe/Moscow' => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)',
                'Europe/Volgograd' => '(GMT+3:00) Europe/Volgograd (Volgograd Time)',
                'Indian/Antananarivo' => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)',
                'Indian/Comoro' => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
                'Indian/Mayotte' => '(GMT+3:00) Indian/Mayotte (Eastern African Time)',
                'Asia/Tehran' => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
                'Asia/Baku' => '(GMT+4:00) Asia/Baku (Azerbaijan Time)',
                'Asia/Dubai' => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
                'Asia/Muscat' => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
                'Asia/Tbilisi' => '(GMT+4:00) Asia/Tbilisi (Georgia Time)',
                'Asia/Yerevan' => '(GMT+4:00) Asia/Yerevan (Armenia Time)',
                'Europe/Samara' => '(GMT+4:00) Europe/Samara (Samara Time)',
                'Indian/Mahe' => '(GMT+4:00) Indian/Mahe (Seychelles Time)',
                'Indian/Mauritius' => '(GMT+4:00) Indian/Mauritius (Mauritius Time)',
                'Indian/Reunion' => '(GMT+4:00) Indian/Reunion (Reunion Time)',
                'Asia/Kabul' => '(GMT+4:30) Asia/Kabul (Afghanistan Time)',
                'Asia/Aqtau' => '(GMT+5:00) Asia/Aqtau (Aqtau Time)',
                'Asia/Aqtobe' => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)',
                'Asia/Ashgabat' => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)',
                'Asia/Ashkhabad' => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)',
                'Asia/Dushanbe' => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)',
                'Asia/Karachi' => '(GMT+5:00) Asia/Karachi (Pakistan Time)',
                'Asia/Oral' => '(GMT+5:00) Asia/Oral (Oral Time)',
                'Asia/Samarkand' => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)',
                'Asia/Tashkent' => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)',
                'Asia/Yekaterinburg' => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)',
                'Indian/Kerguelen' => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)',
                'Indian/Maldives' => '(GMT+5:00) Indian/Maldives (Maldives Time)',
                'Asia/Calcutta' => '(GMT+5:30) Asia/Calcutta (India Standard Time)',
                'Asia/Colombo' => '(GMT+5:30) Asia/Colombo (India Standard Time)',
                'Asia/Kolkata' => '(GMT+5:30) Asia/Kolkata (India Standard Time)',
                'Asia/Katmandu' => '(GMT+5:45) Asia/Katmandu (Nepal Time)',
                'Antarctica/Mawson' => '(GMT+6:00) Antarctica/Mawson (Mawson Time)',
                'Antarctica/Vostok' => '(GMT+6:00) Antarctica/Vostok (Vostok Time)',
                'Asia/Almaty' => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)',
                'Asia/Bishkek' => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)',
                'Asia/Dacca' => '(GMT+6:00) Asia/Dacca (Bangladesh Time)',
                'Asia/Dhaka' => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)',
                'Asia/Novosibirsk' => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)',
                'Asia/Omsk' => '(GMT+6:00) Asia/Omsk (Omsk Time)',
                'Asia/Qyzylorda' => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)',
                'Asia/Thimbu' => '(GMT+6:00) Asia/Thimbu (Bhutan Time)',
                'Asia/Thimphu' => '(GMT+6:00) Asia/Thimphu (Bhutan Time)',
                'Indian/Chagos' => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)',
                'Asia/Rangoon' => '(GMT+6:30) Asia/Rangoon (Myanmar Time)',
                'Indian/Cocos' => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)',
                'Antarctica/Davis' => '(GMT+7:00) Antarctica/Davis (Davis Time)',
                'Asia/Bangkok' => '(GMT+7:00) Asia/Bangkok (Indochina Time)',
                'Asia/Ho_Chi_Minh' => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)',
                'Asia/Hovd' => '(GMT+7:00) Asia/Hovd (Hovd Time)',
                'Asia/Jakarta' => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)',
                'Asia/Krasnoyarsk' => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)',
                'Asia/Phnom_Penh' => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)',
                'Asia/Pontianak' => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)',
                'Asia/Saigon' => '(GMT+7:00) Asia/Saigon (Indochina Time)',
                'Asia/Vientiane' => '(GMT+7:00) Asia/Vientiane (Indochina Time)',
                'Indian/Christmas' => '(GMT+7:00) Indian/Christmas (Christmas Island Time)',
                'Antarctica/Casey' => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))',
                'Asia/Brunei' => '(GMT+8:00) Asia/Brunei (Brunei Time)',
                'Asia/Choibalsan' => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)',
                'Asia/Chongqing' => '(GMT+8:00) Asia/Chongqing (China Standard Time)',
                'Asia/Chungking' => '(GMT+8:00) Asia/Chungking (China Standard Time)',
                'Asia/Harbin' => '(GMT+8:00) Asia/Harbin (China Standard Time)',
                'Asia/Hong_Kong' => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)',
                'Asia/Irkutsk' => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)',
                'Asia/Kashgar' => '(GMT+8:00) Asia/Kashgar (China Standard Time)',
                'Asia/Kuala_Lumpur' => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)',
                'Asia/Kuching' => '(GMT+8:00) Asia/Kuching (Malaysia Time)',
                'Asia/Macao' => '(GMT+8:00) Asia/Macao (China Standard Time)',
                'Asia/Macau' => '(GMT+8:00) Asia/Macau (China Standard Time)',
                'Asia/Makassar' => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)',
                'Asia/Manila' => '(GMT+8:00) Asia/Manila (Philippines Time)',
                'Asia/Shanghai' => '(GMT+8:00) Asia/Shanghai (China Standard Time)',
                'Asia/Singapore' => '(GMT+8:00) Asia/Singapore (Singapore Time)',
                'Asia/Taipei' => '(GMT+8:00) Asia/Taipei (China Standard Time)',
                'Asia/Ujung_Pandang' => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)',
                'Asia/Ulaanbaatar' => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)',
                'Asia/Ulan_Bator' => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)',
                'Asia/Urumqi' => '(GMT+8:00) Asia/Urumqi (China Standard Time)',
                'Australia/Perth' => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))',
                'Australia/West' => '(GMT+8:00) Australia/West (Western Standard Time (Australia))',
                'Australia/Eucla' => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))',
                'Asia/Dili' => '(GMT+9:00) Asia/Dili (Timor-Leste Time)',
                'Asia/Jayapura' => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)',
                'Asia/Pyongyang' => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)',
                'Asia/Seoul' => '(GMT+9:00) Asia/Seoul (Korea Standard Time)',
                'Asia/Tokyo' => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)',
                'Asia/Yakutsk' => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)',
                'Australia/Adelaide' => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))',
                'Australia/Broken_Hill' => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))',
                'Australia/Darwin' => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))',
                'Australia/North' => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))',
                'Australia/South' => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))',
                'Australia/Yancowinna' => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))',
                'Antarctica/DumontDUrville' => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)',
                'Asia/Sakhalin' => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)',
                'Asia/Vladivostok' => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)',
                'Australia/ACT' => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))',
                'Australia/Brisbane' => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))',
                'Australia/Canberra' => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))',
                'Australia/Currie' => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))',
                'Australia/Hobart' => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))',
                'Australia/Lindeman' => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))',
                'Australia/Melbourne' => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))',
                'Australia/NSW' => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))',
                'Australia/Queensland' => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))',
                'Australia/Sydney' => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))',
                'Australia/Tasmania' => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))',
                'Australia/Victoria' => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))',
                'Australia/LHI' => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)',
                'Australia/Lord_Howe' => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)',
                'Asia/Magadan' => '(GMT+11:00) Asia/Magadan (Magadan Time)',
                'Antarctica/McMurdo' => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)',
                'Antarctica/South_Pole' => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)',
                'Asia/Anadyr' => '(GMT+12:00) Asia/Anadyr (Anadyr Time)',
                'Asia/Kamchatka' => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)'
            );
                
        }
    }

    if(!function_exists('deviceTime'))
    {
        function deviceTime($dateFormatString)
        { 
            $responseTime = 21;
            $tz = getCurrentUserTimeZone();
            $date = new DateTime(date('m/d/Y h:i:s a', time()));
            $date->setTimezone(new DateTimeZone($tz));
            return $date->format($dateFormatString);
        }
    }

    if(!function_exists('appointmentCount')){
        function appointmentCount()
        {
        if(Auth::check()){
            if (Auth::user()->type == 'seller') {
                $appointments = Booking::where('seller_id', Auth::user()->id)->where('state','0')->get();
            } else {
                $appointments = Booking::where('buyer_id', Auth::user()->id)->where('state', '0')->get();
            }

            return ['appointment_count'=>count($appointments) ,'appointments'=> $appointments];
            
            }
        }
    }
